# Generated by Django 5.0.4 on 2024-08-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default='32-856', max_length=6, verbose_name='Postal Code'),
        ),
    ]
