# Generated by Django 5.1.5 on 2025-02-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                help_text="Mailing or collection address",
                max_length=100,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="secondary_email",
            field=models.EmailField(
                help_text="Emergency email if primary email is lost",
                max_length=50,
                verbose_name="Secondary Email",
            ),
        ),
    ]
