STANDARD_PARCEL_LOCKERS__DELIVERY = "Standard Parcel lockers"
EXPRESS_PARCEL_LOCKERS__DELIVERY = "Express Parcel lockers"
EXTRA_EXPRESS_PARCEL_LOCKERS__DELIVERY = "Extra Express Parcel lockers"

STANDARD_IN_HOUSE__DELIVERY = "Standard In-house"
EXPRESS_IN_HOUSE__DELIVERY = "Express In-house"
EXTRA_EXPRESS_IN_HOUSE__DELIVERY = "Extra Express In-house"

STANDARD_REMOTE__DELIVERY = "Standard Remote"
EXPRESS_REMOTE__DELIVERY = "Express Remote"
EXTRA_EXPRESS_REMOTE__DELIVERY = "Extra Express Remote"

DELIVERY_CHOICES = (
    (1, STANDARD_PARCEL_LOCKERS__DELIVERY),
    (2, EXPRESS_PARCEL_LOCKERS__DELIVERY),
    (3, EXTRA_EXPRESS_PARCEL_LOCKERS__DELIVERY),
    (4, STANDARD_IN_HOUSE__DELIVERY),
    (5, EXPRESS_IN_HOUSE__DELIVERY),
    (6, EXTRA_EXPRESS_IN_HOUSE__DELIVERY),
    (7, STANDARD_REMOTE__DELIVERY),
    (8, EXPRESS_REMOTE__DELIVERY),
    (9, EXTRA_EXPRESS_REMOTE__DELIVERY),
)
