# Generated by Django 5.0.4 on 2025-01-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="product",
            new_name="products",
        ),
    ]
