# Generated by Django 5.1.5 on 2025-02-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("products", models.ManyToManyField(to="products.product")),
            ],
            options={
                "verbose_name_plural": "Inventories",
            },
        ),
    ]
