# Generated by Django 5.0.4 on 2025-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="Products which are included in this inventory",
                        related_name="inventory",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventories",
            },
        ),
    ]
