# Generated by Django 5.0.4 on 2024-10-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
