# Generated by Django 5.0.4 on 2025-04-24 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0002_initial"),
        ("products", "0003_productdimension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="products",
            field=models.ManyToManyField(
                help_text="Products which are included in this inventory",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="vendor",
            field=models.ForeignKey(
                help_text="Owner of this inventory",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
