# Generated by Django 5.0.4 on 2025-01-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="product",
            new_name="products",
        ),
    ]
