# Generated by Django 5.0.4 on 2024-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=-628, max_length=6),
            preserve_default=False,
        ),
    ]
