# Generated by Django 5.0.4 on 2024-08-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
