# Generated by Django 5.0.4 on 2024-08-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_price_productorder_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
