# Generated by Django 5.0.4 on 2024-09-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='wishlist',
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.BooleanField(default=False),
        ),
    ]
