# Generated by Django 5.0.4 on 2024-09-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
    ]
