# Generated by Django 5.0.4 on 2025-06-04 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Standard Parcel lockers"),
                            (2, "Express Parcel lockers"),
                            (3, "Extra Express Parcel lockers"),
                            (4, "Standard In-house"),
                            (5, "Express In-house"),
                            (6, "Extra Express In-house"),
                            (7, "Standard Remote"),
                            (8, "Express Remote"),
                            (9, "Extra Express Remote"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (1, "Standard Parcel lockers"),
                            (2, "Express Parcel lockers"),
                            (3, "Extra Express Parcel lockers"),
                            (4, "Standard In-house"),
                            (5, "Express In-house"),
                            (6, "Extra Express In-house"),
                            (7, "Standard Remote"),
                            (8, "Express Remote"),
                            (9, "Extra Express Remote"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
                ),
                ("delivery_average_time", models.IntegerField()),
                (
                    "max_length",
                    models.DecimalField(
                        decimal_places=2,
                        default=300,
                        help_text="Length in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Length cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                300.0, message="Length cannot be more than 300 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "max_width",
                    models.DecimalField(
                        decimal_places=2,
                        default=150,
                        help_text="Width in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Width cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                150.0, message="Width cannot be more than 150 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "max_height",
                    models.DecimalField(
                        decimal_places=2,
                        default=120,
                        help_text="Height in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Height cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                120.0, message="Height cannot be more than 120 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Weight in kg",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Weight cannot be less than 0.10 kg"
                            ),
                            django.core.validators.MaxValueValidator(
                                50.0, message="Weight cannot be more than 50 kg"
                            ),
                        ],
                    ),
                ),
                (
                    "weight_unit",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Weight unit only in kilograms"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deliveries",
            },
        ),
    ]
