# Generated by Django 5.0.4 on 2025-04-24 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="height",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Height in cm",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.1, message="Height cannot be less than 0.10 cm"
                    ),
                    django.core.validators.MaxValueValidator(
                        120.0, message="Height cannot be more than 120 cm"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="length",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Length in cm",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.1, message="Length cannot be less than 0.10 cm"
                    ),
                    django.core.validators.MaxValueValidator(
                        300.0, message="Length cannot be more than 300 cm"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Weight in kg",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.1, message="Weight cannot be less than 0.10 kg"
                    ),
                    django.core.validators.MaxValueValidator(
                        50.0, message="Weight cannot be more than 50 kg"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="weight_unit",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="Weight unit only in kilograms"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Width in cm",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.1, message="Width cannot be less than 0.10 cm"
                    ),
                    django.core.validators.MaxValueValidator(
                        150.0, message="Width cannot be more than 150 cm"
                    ),
                ],
            ),
        ),
    ]
