# Generated by Django 5.0.4 on 2025-04-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_delivery_height_delivery_length_delivery_weight_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="height",
            new_name="max_height",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="length",
            new_name="max_length",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="weight",
            new_name="max_weight",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="width",
            new_name="max_width",
        ),
    ]
