# Generated by Django 5.0.4 on 2025-06-04 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Does not need to be unique", max_length=100
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        validators=[products.validators.validate_minimal_price],
                    ),
                ),
                (
                    "miniature_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Limit 100 marks",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Limit 400 marks",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=9),
                ),
                (
                    "units_of_measurement",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Piece"),
                            (2, "Grams"),
                            (3, "Kilograms"),
                            (4, "Liters"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "reviews",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
                ),
                ("is_sale", models.BooleanField(default=False)),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        validators=[products.validators.validate_minimal_price],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Check for similar products",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Length in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Length cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                300.0, message="Length cannot be more than 300 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Width in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Width cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                150.0, message="Width cannot be more than 150 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Height cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                120.0, message="Height cannot be more than 120 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Weight cannot be less than 0.10 kg"
                            ),
                            django.core.validators.MaxValueValidator(
                                50.0, message="Weight cannot be more than 50 kg"
                            ),
                        ],
                    ),
                ),
                (
                    "weight_unit_kg",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Weight unit"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "miniature",
                    models.BooleanField(
                        default=False,
                        help_text="This image will be display on dashboard",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        default="uploads/product/default.jpg",
                        upload_to="uploads/product/",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
