# Generated by Django 5.1.5 on 2025-02-15 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Does not need to be unique", max_length=100
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "miniature_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Limit 100 marks",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Limit 400 marks",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=9),
                ),
                (
                    "units_of_measurement",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Piece"),
                            (2, "Grams"),
                            (3, "Kilograms"),
                            (4, "Liters"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "reviews",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
                ),
                ("is_sale", models.BooleanField(default=False)),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Check for similar products",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "miniature",
                    models.BooleanField(
                        default=False,
                        help_text="This image will be display on dashboard",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        default="uploads/product/default.jpg",
                        upload_to="uploads/product/",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
