# Generated by Django 5.0.4 on 2024-10-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(default='media/brak_jpg.jpg', upload_to='uploads/product/'),
        ),
    ]
