# Generated by Django 5.0.4 on 2025-04-08 17:06

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=6,
                validators=[products.models.validate_minimal_price],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=6,
                validators=[products.models.validate_minimal_price],
            ),
        ),
    ]
