# Generated by Django 5.0.4 on 2024-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.AddField(
            model_name='product',
            name='units_of_measurement',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Piece'), (2, 'Grams'), (3, 'Liters')], default=1),
        ),
    ]
