# Generated by Django 5.0.4 on 2024-10-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.FileField(
                default="media/uploads/product/brak_jpg.jpg",
                upload_to="uploads/product/",
            ),
        ),
    ]
