# Generated by Django 5.0.4 on 2025-04-24 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_name_alter_product_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Length in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Length cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                300.0, message="Length cannot be more than 300 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Width in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Width cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                150.0, message="Width cannot be more than 150 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Height cannot be less than 0.10 cm"
                            ),
                            django.core.validators.MaxValueValidator(
                                120.0, message="Height cannot be more than 120 cm"
                            ),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.1, message="Weight cannot be less than 0.10 kg"
                            ),
                            django.core.validators.MaxValueValidator(
                                50.0, message="Weight cannot be more than 50 kg"
                            ),
                        ],
                    ),
                ),
                (
                    "weight_unit",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Piece"),
                            (2, "Grams"),
                            (3, "Kilograms"),
                            (4, "Liters"),
                        ],
                        default=3,
                        help_text="Weight unit",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
