# Generated by Django 5.0.4 on 2024-08-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_of_measurement',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Piece'), (2, 'Grams'), (3, 'Kilograms'), (4, 'Liters')], default=1),
        ),
    ]
