# Generated by Django 5.0.4 on 2025-05-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productdimension"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdimension",
            name="weight_unit",
        ),
        migrations.AddField(
            model_name="productdimension",
            name="weight_unit_kg",
            field=models.PositiveSmallIntegerField(default=3, help_text="Weight unit"),
        ),
    ]
