# Generated by Django 5.0.4 on 2024-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='uploads/product/'),
        ),
    ]
