# Generated by Django 5.0.4 on 2024-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.FileField(
                default="uploads/product/default.jpg", upload_to="uploads/product/"
            ),
        ),
    ]
