# Generated by Django 5.1.5 on 2025-02-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Check for similar products",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Limit 400 marks",
                max_length=400,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="miniature_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Limit 100 marks",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Does not need to be unique", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="miniature",
            field=models.BooleanField(
                default=False, help_text="This image will be display on dashboard"
            ),
        ),
    ]
